name: CustomActionGetWorkflow
on: 
  workflow_dispatch:

jobs:
  changeApproval:
    name: ServiceNow Change Approval
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@v1.34.2
        id: create
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approval'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","assignment_group":"a715cd759f2002002920bde8132e7018","description":"Automated Software Deployment.","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '3600'
  custom_action_get:
    needs: changeApproval
    runs-on: ubuntu-latest
    name: A Job to get change request
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Custom Action Update Step
        uses: ./ # Uses an action in the root directory
        
        id: get
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          change-details: '{"build_number":"","pipeline_name":"maheshganji/custom-action-get/CustomActionGetWorkflow","stage_name":"ServiceNow Change Approval"}' #Working Version
  custom_action_update:
    runs-on: ubuntu-latest
    name: A Job to Update Change
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Custom Action Update Step
        uses: actions/custom-action-update@v.1 # Uses an action in the root directory
        id: update
        with:
          #change-request-number: 'CHG0030012' # Closed CR
          change-request-number: 'CHG0030017' # Active CR
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          change-request-details: '{ "short_description": "Test description in Updated by Github custom Action - 123","description":"123 - Automated Software Deployment.","work_notes":"Updated by Github Action Custom Update -123"}' #Working Version

